### ISSUE TITLE
A trivial issue to run example

### ISSUE THREAD

**Issue by sirius226** [heckpsi-lab/em-midori#2] opened 2016-10-04 15:54 UTC
Maybe put`require 'em-midori'` in routes.rb after gem install? `require '../lib/em-midori' ` cause some require issues for ruby 2.3.0:

`require.rb:55:in `require': cannot load such file -- em-midori/const (LoadError)
	from /Users/chen.l.li/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/chen.l.li/scripts/em-midori/lib/em-midori.rb:1:in `<top (required)>'
	from /Users/chen.l.li/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/chen.l.li/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from route.rb:1:in `<main>'`

**Comment by dsh0416** [comment] 2016-10-04 19:19
Caused by a recent commit for solving duplicated includes in gemspec.
Fixed in [faeb1a2da5e6b565242458866fe1c88908b97507](https://github.com/heckpsi-lab/em-midori/commit/faeb1a2da5e6b565242458866fe1c88908b97507)
If you want to use published version, but not dev branch, use `require 'em-midori'` instead. 
`require '../lib/em-midori'` is designed for using developing files to test.

**Closed by dsh0416** 2016-10-04 19:19 UTC
